runners:
  - name: "gcp-cirun-bencher"
    cloud: "gcp"
    instance_type: "c4-highcpu-8"
    region: us-central1-f
    machine_image: ubuntu-2404-noble-amd64
    preemptible: false
    labels:
      - "cirun-gcp-bencher"
    extra_config:
      project_id: "firefox.gcp.mozilla.com/developers/moz-fx-dev-leggert-cirun"
