runners:
  - name: "gcp-cirun-bencher"
    cloud: "gcp"
    instance_type: "c4-highcpu-8"
    region: us-central1-f
    machine_image: ubuntu-2404-noble-amd64
    preemptible: false
    labels:
      - "cirun-gcp-bencher"
    extra_config:
      project_id: lateral-booster-464513-i7
      networkInterfaces:
        - stackType: IPV4_ONLY
          subnetwork: projects/lateral-booster-464513-i7/regions/us-central1-f/subnetworks/moz-fx-dev-leggert-cirun
